products = [
        {
            '_id':'1',
            'name':'shoes',
            'brand':'bata',
            'image':'/images/Splash_Page_Femme.jpg',
            'dis':'This is high quality standard level shoe',
            'category':'shoe',
            'price':80,
            'rating':3.8,
            'number_reviews':12,
            'productInStock':0,
        },
        {
            '_id':'2',
            'name':'Shirt',
            'brand':'gucci',
            'image':'/images/18144566_0_casual-shirt-for-men.jpg',
            'dis':'This is high quality standard level shirt',
            'category':'cloth',
            'price':40,
            'rating':4.6,
            'number_reviews':14,
            'productInStock':20,
        },
        {
            '_id':'3',
            'name':'Laptop',
            'brand':'Lenuvo',
            'image':'/images/71h6PpGaz9L._AC_SL1500_.jpg',
            'dis':'This is high quality standard level laptop',
            'category':'Electronic',
            'price':700,
            'rating':3.5,
            'number_reviews':4,
            'productInStock':20,
        },
        {
            '_id':'4',
            'name':'bag',
            'brand':'gucci',
            'image':'/images/Avery_Mini_Caramel_1_1024x1024.jpg',
            'dis':'This is high quality standard level bag',
            'category':'bag',
            'price':20,
            'rating':2.5,
            'number_reviews':24,
            'productInStock':20,
        },
        {
            '_id':'5',
            'name':'Mobile',
            'brand':'Oppo',
            'image':'/images/LMK315IM-350-03.jpg',
            'dis':'This is high quality standard level mobile',
            'category':'electronic',
            'price':400,
            'rating':5.0,
            'number_reviews':20,
            'productInStock':20,
        },
        {
            '_id':'6',
            'name':'Shirt',
            'brand':'gucci',
            'image':'/images/02fe9c5bb339c424b77b0aa307dd58ad.jpg',
            'dis':'This is high quality standard level shirt',
            'category':'cloth',
            'price':40,
            'rating':4.8,
            'number_reviews':52,
            'productInStock':20,
        },
        {
            '_id':'7',
            'name':'Watch',
            'brand':'N/A',
            'image':'/images/140601_RolexYachtmaster.jpg',
            'dis':'This is high quality standard level watch',
            'category':'electronic',
            'price':50,
            'rating':5.0,
            'number_reviews':42,
            'productInStock':20,
        },
        {
            '_id':'8',
            'name':'Cute Cloth',
            'brand':'gucci',
            'image':'/images/af1cc4d4353b1791b99c108a34e900c3.jpg',
            'dis':'This is high quality standard level cloth',
            'category':'cloth',
            'price':20,
            'rating':5.0,
            'number_reviews':56,
            'productInStock':20,
        },
]
